# Generated by Django 5.1.1 on 2024-09-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField()),
                ('dataNum', models.IntegerField()),
                ('data', models.TextField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_managment.node')),
            ],
        ),
    ]
