# Generated by Django 5.1.1 on 2024-09-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_managment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='dataNum',
        ),
        migrations.AlterField(
            model_name='data',
            name='hash',
            field=models.TextField(unique=True),
        ),
    ]
