# Generated by Django 5.1.1 on 2024-09-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_managment', '0002_remove_data_datanum_alter_data_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='creator_node',
            field=models.CharField(default=32, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='data',
            name='node',
        ),
        migrations.AddField(
            model_name='data',
            name='node',
            field=models.ManyToManyField(to='node_managment.node'),
        ),
    ]
