# Generated by Django 5.1.1 on 2024-09-28 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_managment', '0003_data_creator_node_remove_data_node_data_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='node',
        ),
        migrations.AddField(
            model_name='data',
            name='node',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='node_managment.node'),
            preserve_default=False,
        ),
    ]
