# Generated by Django 5.1.1 on 2024-09-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_managment', '0004_remove_data_node_data_node'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='node',
        ),
        migrations.AddField(
            model_name='data',
            name='node',
            field=models.ManyToManyField(to='node_managment.node'),
        ),
    ]
